Created Event and Fund Model #4
RCDD-202203-TUR-BEW/backend-capstone-turkey-pebble-work pull request #19
Opened 2022-07-23 16:08 UTC by sarahmood

## **Event and Fund models setup.** 

All fields required were implemented. 
I created two Virtual fields one is **gatheredFund** to represent a sum of gathered donations, and **remainingFund** to  represent  how much left to complete required fund. 

Virtual fields needs extra attention if they implemented in correct way or need any changes.

2022-07-23 19:01 UTC, muhammed-shihebi requested changes
Nice work! there are some problems though. 
In addition to the ones mentioned in the comments, you have to delete the package-lock.json and start using the yarn if you are not. 
So you have to: 
1. install yarn 
2. run the program using: `yarn && yarn start`
3. delete the package-lock.json

2022-07-23 19:01 UTC, muhammed-shihebi commented on src/models/funds
> +});
You can add this line after the schema so that the virtual values are populated automatically when we query a fund object. 
`}, { toJSON: { virtuals: true } }, { toObject: { virtuals: true } });`

2022-07-23 19:01 UTC, muhammed-shihebi commented on src/models/funds
> +  return sum(this.donations[0].amount);
This will only return the value of the first donation, 
```
let sum;
donations.forEach(donation => {
  sum += donation.amount;
});
return sum; 
```

2022-07-23 19:01 UTC, muhammed-shihebi commented on src/models/funds
> +  return this.targetFund - this.donations[0].amount;
Same here, you have to calculate the sum first. But try to use the `this.gatheredFund` value first. If it was undefined, just calculate the sum again and return the following: 
```
return this.targetFund - sum;
```

2022-07-23 22:48 UTC, sarahmood commented on src/models/funds
> +});
I thought this done when query the field! Good to know!

2022-07-24 07:30 UTC, muhammed-shihebi requested changes

2022-07-24 07:30 UTC, muhammed-shihebi commented on src/models/funds
> +  donations.forEach((donation) => {
To get rid of the errors, you have to say `this.donations.forEach(...`

2022-07-24 10:35 UTC, muhammed-shihebi approved these changes

2022-07-25 07:41 UTC, halitbatur requested changes
Looks good, just move the variables and its ready to be merged

2022-07-25 07:41 UTC, halitbatur commented on src/models/events
> +    enum: [
can we move this to a variable?

2022-07-25 07:41 UTC, halitbatur commented on src/models/funds
> +        'No Poverty',
same here this is the same enum we have in events so lets move it to a shared variable folder and use it here, please contact @mehmettbaki and agree on what the naming will be for this file/folder that u will save the variables in

2022-07-25 18:25 UTC, muhammed-shihebi approved these changes
Looks good

2022-07-26 06:59 UTC, halitbatur approved these changes

2022-07-26 06:59 UTC, halitbatur commented on src/utility/variables.js
> +];
just a new line here after this

2022-07-26 14:22 UTC, merged