Muhammed shihebi/issue6
RCDD-202203-TUR-BEW/backend-capstone-turkey-pebble-work pull request #32
Opened 2022-07-28 17:44 UTC by muhammed-shihebi

Here is a list of the things done in this pull request: 

- Sign in/out/up endpoints 
- User email verification endpoint using nodemailer
- Several validation middlewares
- A mail sending service with nodemailer 
- An error handling middleware 
- Comprehensive integration tests for the mentioned endpoints 
- Some edits on the fund and user schemas 
- An authentication middleware 

Note: due to its size, we have decided to split the rest of the tasks that should be handled in this issue to several other issues: 
1. Writing a unit test for the mail service and a mock test for `sendVerificationEmail` implemented in the auth controller. 
2. Documentation with Swagger for the implemented endpoints 
3. Create a connection to the image storage database and edit endpoints and tests accordingly

2022-07-29 12:29 UTC, ramaalshaban approved these changes

2022-07-31 09:05 UTC, halitbatur requested changes
Great work! just a few tweaks and its ready to be merged

2022-07-31 09:05 UTC, halitbatur commented on src/controllers/auth.js
> +const HASH_ROUNDS = 10;
can we move this and the following to the lib file with all the other consts?

2022-07-31 09:05 UTC, halitbatur commented on src/controllers/auth.js
> +    const subject = 'Verify your account';
we can move this to a const in the lib file too

2022-07-31 09:05 UTC, halitbatur commented on src/controllers/auth.js
> +        // check if baseUser already exists
I dont think this comment is needed since the upcoming query is straight forward

2022-07-31 09:05 UTC, halitbatur commented on src/controllers/auth.js
> +        const oldUser = await BaseUser.findOne({ email: req.body.email });
variable name here is a bit confusing, maybe we can change it to `alreadyExistingUser`

2022-07-31 09:05 UTC, halitbatur commented on src/controllers/auth.js
> +        });
can we put new lines between consts and if conditions here?

2022-07-31 09:05 UTC, halitbatur commented on src/controllers/auth.js
> +        }
new line

2022-07-31 09:05 UTC, halitbatur commented on src/controllers/auth.js
> +        // create token
remove comment

2022-07-31 09:05 UTC, halitbatur commented on src/routes/auth.js
> +const MAX_IMAGE_SIZE = 1024 * 1024 * 10; // 10MB
move this to the lib file

2022-07-31 09:05 UTC, halitbatur commented on src/routes/auth.js
> +    handleValidation,
can we add the handle validation to all the routers instead of adding it to each of the routes

2022-07-31 09:05 UTC, halitbatur commented on src/utility/validation.js
> +const MAX_IMAGE_SIZE = 1024 * 1024 * 10; // 10MB
use it from the lib when u move the other one

2022-08-01 10:13 UTC, halitbatur approved these changes
Looks good

2022-08-01 10:14 UTC, merged