implement post event/join endpoind #13
RCDD-202203-TUR-BEW/backend-capstone-turkey-pebble-work pull request #38
Opened 2022-08-03 14:20 UTC by sarahmood

### The following were added
- event/:id/join route
- validation params
- integration test
- swagger docs

2022-08-04 09:39 UTC, muhammed-shihebi commented on src/controllers/auth.js
> -
Please delete unneeded console logs onece you are done with them.

2022-08-04 09:46 UTC, muhammed-shihebi commented on src/app.js
> +const options = {
In the dev branch, these options are moved to variables.js 
While merging your branch, just make sure to remove them from here and get the options from the variables.js file

2022-08-04 09:48 UTC, muhammed-shihebi commented on src/routes/events.js
> +    '/:id/join',
Join is a verb. Endpoints should not contain verbs. Now you are saying something "Post user as join." Better is to say "Post user as volunteer. 
So, I think this should be changed to volunteer.

2022-08-04 09:56 UTC, muhammed-shihebi commented on src/controllers/events.js
> +        await EventModel.findByIdAndUpdate(req.params.id, {
You are not checking first if the user is alreay in the array of confirmedVolunteers. This array should not contain any duplicates.

2022-08-04 09:57 UTC, muhammed-shihebi commented on src/controllers/events.js
> +        await User.findByIdAndUpdate(req.user.id, {
Same as above.

2022-08-04 11:03 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +tags:
This file contains some minor indentation issues. These issues are fixed in this gist: https://gist.github.com/muhammed-shihebi/9d195c5b5a69e27c2f8ad87c6107f730

2022-08-04 11:04 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +            - auth_cookie: []
You are using an auth_cookie without define it first. This is also fixed in the gist.

2022-08-04 11:09 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +    responses:
Pay attention to indentation!

2022-08-04 11:09 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +    Event:
This schema should be deleted since you are not using it.

2022-08-04 12:39 UTC, muhammed-shihebi commented on src/routes/__tests__/events.test.js
> +const request = require('supertest');
Your test is not working for several reasons that are hard to explain. For that, I created a gist that contains a working test for your endpoint. The rest of the test you can do yourself :)
https://gist.github.com/muhammed-shihebi/3b4ab4d00c73f5c78cb76ee681259bff

2022-08-04 12:40 UTC, muhammed-shihebi commented on src/controllers/auth.js
> +        console.log(token);
Please delete unneeded console logs onece you are done with them.

2022-08-04 12:42 UTC, muhammed-shihebi requested changes
Other than the test file and swagger, your code is very good and clean. I have suggested some changes in your endpoint and added examples for swagger and the test. Hope it helps 😁

2022-08-08 14:55 UTC, muhammed-shihebi approved these changes

2022-08-09 06:57 UTC, halitbatur approved these changes
Just 1 change

2022-08-09 06:57 UTC, halitbatur commented on src/controllers/events.js
> +        const JoinedUser = await EventModel.findOne({
Variables need to be camelCased

2022-08-10 13:17 UTC, merged