Mehmettbaki/issue11
RCDD-202203-TUR-BEW/backend-capstone-turkey-pebble-work pull request #44
Opened 2022-08-05 20:09 UTC by mehmettbaki

create post /events and add docs/event.yaml and test file it is not completed

2022-08-05 22:32 UTC, muhammed-shihebi requested changes
Nice work, still needs some work though. You seem to have disabled the `yarn validate` command in .husky. If you want to push without running the tests, it's fine, you can disable the `yarn test`, but validation is required in all cases.

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/utility/validation.js
> +    body('category').exists().isString()
The category is changed to categories in the dev branch. It is an array now, make sure you update your validation accordingly. 
Something like: 
```
    body('categories')
        .exists()
        .isArray({ min: 1 })
        .withMessage('categories must be an unempty array')
        .custom((array) =>
            array.every(
                (category) =>
                    isString(category) &&
                    variables.CATEGORIES.includes(category)
            )
        )
        .withMessage('interests must be an array of valid interests'),
```

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/docs/event.yaml
> + - name: create a new event
add a space before -name and change tag to Event instead of this. 
```
tags:
  - name: Event
```

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +        - event
```
- Event
```

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +        400:
I can't see where your endpoint has this error. you probably should remove this.

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +        category:
category => categories should be an array. 
```
        categories:
          type: array
          items:
            type: string
            enum:
              - No Poverty
```

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +        category:
the same thing wit categories

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/routes/events.js
> +
delete extra line

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/controllers/events.js
> +            `${EVENT_IMAGE_DIR}/${Date.now()}.${getFileExtension(
What is Date.now() my friend? 
The name of the file should be the id of the event so we know to which event an image belongs. 
In the beginning, you don't have the id, so you have to postpone uploading the image until after you create the event.

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/controllers/events.js
> +        const event = await new Event({
Now, this event does not have an id. Instead you can say something like: 
```
const event = await Event.create({...})  
```
which will return an event with an id that you can use while uploading the image. 
After that to save the URL of the image you can say: 
```
event.coverImage = imageUrl; 
await event.save();
```

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/controllers/events.js
> +    } catch (err) {
add console.log(err); 
don't worry about the warrnings.

2022-08-05 22:32 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +          type: decimal
add new line at the end.

2022-08-08 23:40 UTC, muhammed-shihebi requested changes
Nice work, you have fixed most of the errors I have mentioned. However, your code still needs some fixes in my opinion. Husky should run yarn validate when you make commits, did you disable it? If yes, please enable it again, it formats the code and points out errors.

2022-08-08 23:40 UTC, muhammed-shihebi commented on src/docs/event.yaml
>          500:
In addition to 500 and 201, your endpoint contains 422 for validation errors and 401 for missing auth tokens.

2022-08-08 23:40 UTC, muhammed-shihebi commented on src/docs/event.yaml
> +          items:
There should be an indentation after the items property: 
```
items: 
  type: string
  enum: ...
```

2022-08-08 23:40 UTC, muhammed-shihebi commented on src/routes/events.js
>  module.exports = router
There should be always an empty line after the last line.

2022-08-08 23:40 UTC, muhammed-shihebi commented on src/utility/validation.js
> +        .withMessage('interests must be an array of valid interests'),
This is actually my bad :)
categories must be an array of valid category

2022-08-13 12:10 UTC, muhammed-shihebi approved these changes
There were several issues in your code. To speed up the process, I just fixed them quickly and pushed the code. You will still have to merge your branch with the dev branch though.

2022-08-14 14:08 UTC, halitbatur approved these changes

2022-08-14 21:20 UTC, merged