Ramaalshaban/issue15
RCDD-202203-TUR-BEW/backend-capstone-turkey-pebble-work pull request #51
Opened 2022-08-09 11:27 UTC by ramaalshaban

##GET /fund/:id

Includes validation, test and swagger docs

2022-08-09 20:01 UTC, muhammed-shihebi requested changes
This is certainly better code than the previous one you wrote. You are making progress! 
Nevertheless, there are some changes that have to take place before merging. I have also added some examples. Hope this helps.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/app.js
> +app.use('/api/fund', fundRouter);
This should actually be added after the `authMiddleware` since `fundRouter` contains other routes that are not public.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/controllers/funds.js
> +        // const { id } = req.params;
Please delete commented code.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/controllers/funds.js
> +        const requiredUserField = [
Nice

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/controllers/funds.js
> +        return res.status(500).json({ error: 'Internal server error' });
Please add a `console.log(err)` so we can see what is the error in case there was one.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/events.test.js
> +const Funds = require('../../models/fund');
Seems like you deleted the old tests in the events.test.js file and replaced them with funds tests 😅, however, you can leave this as it is, and while merging accept the incoming changes.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +    // id = '619b77dd5c639f35dd2d37c4',
Please delete commented code.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +    // id : '619b77dd5c639f35dd2d37c4',
commented code

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/funds.js
>  module.exports = router;
Why did you delete the extra line :)
There should be an extra line at the end of the file.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +const { ObjectId } = require('mongodb');
Please delete not used code.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +/* eslint-disable consistent-return */
Delete these lines since their problems are solved in the next comments.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +let userId;
This should be `fundId` instead

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +    userId = validFund1._id;
1. `validFund1._id` does not contain a _id property, since it is a normal object and we did not fetch it from the database. 
2. If you want to get the id of the fund do with like this: 
```
const fund1 = await Funds.create(validFund1);
```

3. Replace this with `fundId = fund1.id;`

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +        // const id = '619b77dd5c639f35dd2d37c4';
commented code

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +            .get(`/api/fund/${userId}`)
fundId

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +                expect(res.body[1].content).toEqual('lalalalalalalalala');
`/api/fund/${fundId}` returns one fund not an array, so you have to replace `res.body[1].content` with `res.body.content`. Also, since the content of your funds is the same "lalala...", I suggest that you use the title here instead to make sure you got the correct fund.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +                done();
To get rid of problems, say `return done()` instead

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +            .set('Content-Type', 'application/json')
You have add `.expect('Content-type', /json/)` after this line

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +                done();
return done()

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/routes/__tests__/funds.test.js
> +                done();
return done()

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
> +        - Fund
be consistent with the names of the tags. Use `Fund` overall. In the previous endpoint, you have used Funds, so replace it with Fund.

2022-08-09 20:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
> +/api/fund/:id:
This endpoint should be inside the paths with the other endpoints. 
```
paths:
  /api/fund/: 
    get: 
      ...
  /api/fund/:id:
    get: 
      ...
```

2022-08-09 20:24 UTC, ramaalshaban commented on src/controllers/funds.js
> +        const requiredUserField = [
Ciddi misin @muhammed-shihebi : D

2022-08-09 21:54 UTC, muhammed-shihebi commented on src/controllers/funds.js
> +        const requiredUserField = [
Well, it was a nice code hahaha

2022-08-10 10:20 UTC, muhammed-shihebi approved these changes
Nice work!

2022-08-11 11:29 UTC, halitbatur approved these changes

2022-08-11 11:29 UTC, halitbatur commented on src/controllers/funds.js
> +        // const fund = await Funds.findById(id);
why is there commented code here?

2022-08-11 11:29 UTC, halitbatur commented on src/controllers/funds.js
> +async function getOneFund(req, res) {
can be `getSingleFund` or `getFund`

2022-08-11 11:30 UTC, halitbatur commented
@ramaalshaban Few changes and fix the conflicts and it can be ready to be merged

2022-08-11 21:18 UTC, mehmettbaki approved these changes
nice work. keep it up!

2022-08-14 14:25 UTC, halitbatur approved these changes

2022-08-14 16:01 UTC, muhammed-shihebi requested changes
This is very good work @ramaalshaban. There are no problems in the logic of your endpoints and everything is working as expected. 
You requested help on the swagger documentation, so I added several comments that will help you fix the problem you are facing. 

You can use this [gist](https://gist.github.com/muhammed-shihebi/6b267a40db072721d73bdbc62c7c1d41) as a reference where the swagger problems are solved. You can copy and paste it if you want or follow the comments to fix the problems, it is your choice.

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/controllers/funds.js
> +        return res.sendStatus(500);
Please follow our convention and return an error message: 
`return res.status(500).json({ error: 'Internal server error' });`

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/routes/funds.js
> +    '/:id/delete',
I guess you added this because of the conflicts in the swagger docs. Just write this here as usual `/:id` and follow what I have suggested to solve the problem you faced in swagger docs.

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
> +  /api/fund/:id:
One endpoint in swagger can have several verbs like `get` and `delete` like this: 
```
/api/fund/:id:
  get: 
    ...
  delete: 
    ...
```
So, you don't have to add an extra thing to the endpoint like `/delete` to differentiate between endpoints. 

Additionally, instead of using `/api/fund/:id`, you can use `/api/fund/{id}` which will enable the try it now button in the swagger docs page.

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
> +  /api/fund/:
While reviewing your code, I noticed some problems in the responses for the `/api/fund/` endpoint. Since you did not edit this endpoint in this push, I just going to state the problems here. 
1. in response 200 there is a `s` messing in the reference string: 
  `$ref: "#/components/schemas/Fund"`
2. You have 400 as a response but your endpoint does not have this. Instead, you can just add 422 for the validation error: 
  ```
  "422":
    description: This status is returned when the request is missing required fields or has an invalid values.
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/ValidationError"
  ```
3. You could also add the 500 error: 
```
  "500":
    description: Internal Server Error
```

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
> +                schema:
You are returning one fund here, so your 200 response should look like this: 
```
200:
  description: The Fund object with the specified Id 
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Fund"
```
Please note the `s` in schemas and that the object you are referencing is Fund not Event :)

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
> +  /api/fund/:id/delete:
As mentioned, you don't have to add delete at the end, just add a delete verb inside the `/api/fund/{id}` endpoint.

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
> +      responses:
You seem to have forgotten to add a success response (as I did in the delete event docs :)). You need to add a 204 response code like this: 
```
        204:
          description: The fund was deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Fund deleted"
```

Additionally, this endpoint require auth cookie in the request, so you should also add the error case 401, in case a user tires to access this endpoint without being signed in. 

```
        401:
          description: This status is returned if the user is not signed in.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Invalid Token: No authorization token was found"
```

2022-08-14 16:01 UTC, muhammed-shihebi commented on src/docs/funds.yaml
>      Fund:
In your endpoints, I noticed that you are populating the populisherId, so I suggest that you update your fund schema and make the publisherId an object as follows: 

```
publisherId:
  $ref: "#/components/schemas/ShortUser"
```

You can add the ShortUser schema to the schemas as follows: 
```
components:
  schemas:
    ShortUser:
      properties:
        _id:
          type: string
          example: 62e980586aca79a3936917e6
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          example: mail@example.com
        __t:
          type: string
          example: User
        profileImage:
          type: string
          example: https://www.example.com/image.jpg
        fullName:
          type: string
          example: John Doe
        id:
          type: string
          example: 62e980586aca79a3936917e6
    Fund: 
      ...
```

2022-08-14 21:41 UTC, muhammed-shihebi approved these changes
Well done! everything is in order and your PR is ready to be merged.

2022-08-15 17:16 UTC, halitbatur commented
@ramaalshaban lets get the conflicts fixed and merge this PR by tonight

2022-08-16 02:42 UTC, merged