Sarahmood/issue53
RCDD-202203-TUR-BEW/backend-capstone-turkey-pebble-work pull request #71
Opened 2022-08-20 14:10 UTC by sarahmood

## The following were added

GET user / organization routes.
**Note :**  **I separated profiles to be public and private profiles so anyone can view public profile with sensitive data excluded, and user can view its profile with sensitive data exist.** 
validation
swagger docs

2022-08-22 17:21 UTC, muhammed-shihebi requested changes
Great work @sarahmood as always, just few tweaks and it is ready to be merged.

2022-08-22 17:21 UTC, muhammed-shihebi commented on src/docs/organizations.yaml
> +                - multipart/form-data
Why multipart/form-data? 
Your endpoint consumes application/json actually.

2022-08-22 17:21 UTC, muhammed-shihebi commented on src/docs/organizations.yaml
> +                        $ref: '#/components/schemas/ShortUser'
You are using the short user here, but it includes user email and in your endpoint, you are returning only 'id', 'firstName', 'lastName', and 'profileImage'. Consider defining a new schema for your short user.

2022-08-22 17:21 UTC, muhammed-shihebi commented on src/docs/organizations.yaml
> +            responses:
Could you please add the response code of the validation error.

2022-08-22 17:21 UTC, muhammed-shihebi commented on src/docs/organizations.yaml
> +                                $ref: '#/components/schemas/ValidationError'
You can't use $ref and properties at the same time. If you look at your endpoint in swagger, you will see that only the $ref is visible, and non of the stuff in the properties is visible. 

Also, you are referencing the ValidationError, which has a different schema than yours. You have `{message: 'Page not found'}`.

So, you should add both your 404 error and the 422, which is the validation error.

2022-08-22 17:21 UTC, muhammed-shihebi commented on src/docs/organizations.yaml
> +                - multipart/form-data
please use application/json instead

2022-08-22 17:21 UTC, muhammed-shihebi commented on src/docs/users.yaml
> +                - multipart/form-data
application/json

2022-08-22 17:21 UTC, muhammed-shihebi commented on src/docs/users.yaml
> +                - multipart/form-data
application/json

2022-08-22 20:07 UTC, sarahmood commented on src/docs/organizations.yaml
> +                        $ref: '#/components/schemas/ShortUser'
@muhammed-shihebi based on what we discussed, we said to take off email form all users in the project. I fixed that in dev branch and when I merge there will be no email in ShortUser.

2022-08-22 20:09 UTC, sarahmood commented on src/docs/organizations.yaml
> +                        $ref: '#/components/schemas/ShortUser'
okay it is not removed haha! i will fix ShortUser in this PR to not have email

2022-08-23 09:35 UTC, halitbatur commented
@sarahmood any updates on the changes requested, when do you think you will be able to fix it

2022-08-24 09:50 UTC, muhammed-shihebi approved these changes

2022-08-24 10:57 UTC, halitbatur approved these changes

2022-08-24 19:55 UTC, merged