Download needed packages and setup the project folders
RCDD-202203-TUR-BEW/backend-capstone-turkey-pebble-work pull request #9
Opened 2022-07-22 02:36 UTC by laragurol

2022-07-22 14:43 UTC, sarahmood reviewed
All agreed packages and folders were setup. Just make sure to remove couple of unused dependencies mentioned.

2022-07-22 14:43 UTC, sarahmood commented on package.json
> +    "ejs": "^3.1.8",
remove ejs package, since we are not building any views.

2022-07-22 14:43 UTC, sarahmood commented on package.json
> +    "express-ejs-layouts": "^2.5.1",
remove ejs package, since we are not building any views.

2022-07-22 15:01 UTC, halitbatur requested changes
Looks good so far, fix the comments, merge it with the latest master branch and remove the __tests__ folder u created.

2022-07-22 15:01 UTC, halitbatur commented on package.json
> -    "postinstall": "husky install && husky add .husky/pre-commit \"yarn validate-staged\" && husky add .husky/pre-push \"yarn test\""
why is this command removed this shouldn't be removed

2022-07-23 03:30 UTC, laragurol reviewed
-fixed the "main" to src/app.js
-fixed env to initial state 
-reinstalled deleted husky dev 
-fixed deleted command on package.json
-uninstalled ejs and express-ejs-
-deleted tests folder
-deleted code in app file

2022-07-23 09:00 UTC, halitbatur commented
@laragurol could u please do the following:
- Update your dev branch
- Create a new branch for this issue (delete the current branch)
- Download the needed packages only using `yarn` please dont use `npm` cause I see that there's package-lock.json
- and then do another PR

2022-07-23 09:01 UTC, halitbatur commented
For now I will close this PR it has conflicting files, and it uses npm not yarn so it won't be merged.

2022-07-23 09:01 UTC, closed without merging